<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>Haproxy.Editor</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
		<PackageReference Include="ModelContextProtocol.AspNetCore" Version="2.1.0" />
		<PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.2.3" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Haproxy.Editor.Abstractions\Haproxy.Editor.Abstractions.csproj"/>
		<ProjectReference Include="..\Haproxy.Editor.Adapters.Haproxy\Haproxy.Editor.Adapters.Haproxy.csproj"/>
		<ProjectReference Include="..\Haproxy.Editor.Adapters.MongoDB\Haproxy.Editor.Adapters.MongoDB.csproj"/>
		<ProjectReference Include="..\Haproxy.Editor.Core\Haproxy.Editor.Core.csproj"/>
	</ItemGroup>

</Project>
